# Generated by Django 4.2.3 on 2023-07-21 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 21), verbose_name='Дата следующей рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('DA', 'ежедневно'), ('WE', 'еженедельно'), ('MO', 'ежемесячно')], default='DA', max_length=2, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CM', 'completed'), ('CR', 'created'), ('LA', 'launched')], default='CR', max_length=2, verbose_name='Статус рассылки'),
        ),
    ]
