# Generated by Django 4.2.3 on 2023-07-21 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_date_alter_mailing_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата следующей рассылки (дд.мм.гггг)'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(verbose_name='Время начала рассылки (чч:мм:сс)'),
        ),
    ]
