# Generated by Django 4.2.3 on 2023-07-21 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 21, 19, 32, 12, 626353), verbose_name='Время начала рассылки (чч:мм:сс)'),
        ),
    ]
