# Generated by Django 4.2.3 on 2023-07-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='server_request',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ сервера'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='time',
            field=models.DateTimeField(verbose_name='Дата и время последней рассылки'),
        ),
    ]
