# Generated by Django 4.2.3 on 2023-07-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_mailing_clients_alter_mailingattempt_mailing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ('-time',), 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CM', 'Completed')], default='AC', max_length=2, verbose_name='Статус попытки рассылки'),
        ),
    ]
