# Generated by Django 4.2.3 on 2023-07-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailingattempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Дата и время последней рассылки')),
                ('status', models.BooleanField()),
                ('server_request', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ('-time',),
            },
        ),
        migrations.DeleteModel(
            name='MailingAttempt',
        ),
    ]
