# Generated by Django 4.2.3 on 2023-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_mailinglogs_delete_mailingattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='server_request',
            field=models.CharField(max_length=250, verbose_name='Ответ сервера'),
        ),
    ]
